---
# Docker
internal_network: wallet

# Deployment
base_domain: local
base_dir: /opt
wallet_ecosystem_dir: "{{ base_dir}}/wallet-ecosystem"

wallet_frontend: "wallet.{{ base_domain }}"

enterprise_config:
  vid_issuer:
    host: wallet-vid
    port: 8003
    secret: secret
  acme_verifier:
    host: wallet-acme
    port: 8005
    secret: secret
  diploma_issuer:
    host: wallet-diploma
    port: 8000
    secret: secret
  ehic_issuer:
    host: wallet-ehic
    port: 8004
    secret: secret

allow_password: true

# Secrets
secrets_file: "environments/wallet/secrets.yml"
