---
wallet_ecosystem_dir: "{{ base_dir}}/wallet-ecosystem"
wallet_ecosystem_repo_url: "https://github.com/wwWallet/wallet-ecosystem.git"
wallet_ecosystem_version: "master"

allow_password: true

db_config:
  host: wallet-db
  port: 3307
  user: root
  password: root

backend_config:
  url: "{{ wallet_frontend.url }}"
  port: 8002
  secret: secret
  ssl_flag: false
  client_url: "{{ wallet_frontend.url }}/cb"
  origin: "{{ wallet_frontend.url }}"
  notifications: "false"
